version: "3.8"
services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KRAFT_CONTAINER_HOST_NAME: broker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server broker:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kafka-net

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kafka-net

  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kafka-net

networks:
  kafka-net:
