version: "3.8"
services:
  broker:
    platform: linux/amd64
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KRAFT_CONTAINER_HOST_NAME: broker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
    networks:
      - kafka-net

  payment-service:
    image: sample-spring-kafka-microservices/payment-service:1.0-SNAPSHOT
    depends_on:
      - broker
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kafka-net

  stock-service:
    image: sample-spring-kafka-microservices/stock-service:1.0-SNAPSHOT
    depends_on:
      - broker
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kafka-net

networks:
  kafka-net: